apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: "my-app-image:latest"
          ports:
            - containerPort: 80
          env:
            - name: REDIS_HOST
              value: "{{ .Values.redis.fullnameOverride }}"
            - name: REDIS_PORT
              value: "{{ .Values.redis.master.service.port }}"
            - name: REDIS_PASSWORD
              value: "{{ .Values.redis.password }}"
